packages:
- 'packages/types'
- 'packages/signers'
- 'packages/forge'
- 'packages/nwpc'
- 'packages/storage'
- 'packages/hdkeys'
- 'packages/utils'
- 'packages/token'
- 'packages/pocket'
- 'packages/config'
- 'packages/tdk'
- 'packages/booth'
- 'packages/gate'
- '!**/node_modules/**'
