packages:
- 'packages/forge'
- 'packages/nwpc'
- 'packages/storage'
- 'packages/hdkeys'
- 'packages/utils'
- 'packages/token'
- 'packages/pocket'
- 'packages/config'
- 'packages/tdk'
- 'packages/boxoffice'
- 'packages/turnstile'
- '!**/node_modules/**'
